### PR TITLE
fix: tsconfig.json

### PR DESCRIPTION
**Pull request by Fleny113**
Currently the TSConfig.json errors out as the `rootDir` is inherited as "/src" which makes it 0 files and every single other file marked by include (`["."]`) is outside the `rootDir`, creating ~~90 TS errors

### CODE REVIEW

**Review by lts20050703 — APPROVED** [review]
LGTM!

**Comment by lts20050703** [comment]
Why was `allowJS` removed? Also you forgot to update the PR description :)

**Comment by Fleny113** [comment]
> Why was `allowJS` removed? 
Skillz said on discord the prefers not having allowJS and rather in the future rewrite the js files into ts ones

**Review by lts20050703 — APPROVED** [review]
LGTM!

**Pull request merged**
