### PR TITLE
Centralize types and structures

### PR DESCRIPTION
**Pull request by itohatweb**
**Please describe the changes this PR makes and why it should be merged:**
Since there are many different Types etc. files, there should be a centeral centeral file that is exporting all types. So the other files wich are requiring many types do not have so much imports from different files.

Changes still need to be tested.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ayntee** [comment]
Can you change the base branch to `next`?

**Comment by itohatweb** [comment]
New imports were briefly tested and checked again. Code should work.

**Comment by ayntee** [comment]
Merge conflicts :sweat_smile:

**Comment by itohatweb** [comment]
Working on them.

**Comment by itohatweb** [comment]
Moved to #235

**Pull request closed without merging**
