### PR TITLE
feat: bigstring

### PR DESCRIPTION
**Pull request by Skillz4Killz**

### CODE REVIEW

**Comment by lts20050703** [comment]
Check Formatting and Test are failing

**Comment by lts20050703** [comment]
```
./tests/webhook/webhook.test.ts => [webhooks] Webhook related tests ... [webhooks] Create a webhook ... FAILED (310ms)
    error: TypeError: Cannot convert undefined to a BigInt
      return BigInt(snowflake) | 0n;
             ^
        at BigInt (<anonymous>)
        at Object.snowflakeToBigint [as snowflake] (file:///home/runner/work/discordeno/discordeno/util/bigint.ts:4:10)
        at Object.transformWebhook [as webhook] (file:///home/runner/work/discordeno/discordeno/transformers/webhook.ts:7:26)
        at createWebhook (file:///home/runner/work/discordeno/discordeno/helpers/webhooks/createWebhook.ts:35:27)
        at async file:///home/runner/work/discordeno/discordeno/tests/webhook/webhook.test.ts:12:21
./tests/webhook/webhook.test.ts => [webhooks] Webhook related tests ... [webhooks] Get channel webhooks ... FAILED (303ms)
    error: TypeError: Cannot convert undefined to a BigInt
      return BigInt(snowflake) | 0n;
             ^
        at BigInt (<anonymous>)
        at Object.snowflakeToBigint [as snowflake] (file:///home/runner/work/discordeno/discordeno/util/bigint.ts:4:10)
        at Object.transformWebhook [as webhook] (file:///home/runner/work/discordeno/discordeno/transformers/webhook.ts:7:26)
        at createWebhook (file:///home/runner/work/discordeno/discordeno/helpers/webhooks/createWebhook.ts:35:27)
        at async file:///home/runner/work/discordeno/discordeno/tests/webhook/webhook.test.ts:49:20
./tests/webhook/webhook.test.ts => [webhooks] Webhook related tests ... FAILED (1s)
./tests/guilds/events/events.test.ts => [events] unit tests for events ... [scheduled event] edit a scheduled event ... [scheduled events] voice channel events tests ... [scheduled event] edit the scheduled event entity type to external from voice channel. ... ok (17s)
./tests/guilds/events/events.test.ts => [events] unit tests for events ... [scheduled event] edit a scheduled event ... [scheduled events] voice channel events tests ... [scheduled event] edit the scheduled event entity type to voice channel from external type. ... ok (514ms)
./tests/guilds/events/events.test.ts => [events] unit tests for events ... [scheduled event] edit a scheduled event ... [scheduled events] voice channel events tests ... ok (19s)
./tests/guilds/events/events.test.ts => [events] unit tests for events ... [scheduled event] edit a scheduled event ... ok (1m13s)
./tests/guilds/events/events.test.ts => [events] unit tests for events ... ok (1m24s)

 ERRORS 

[webhooks] Webhook related tests => ./tests/webhook/webhook.test.ts:5:6
error: Error: 2 test steps failed.
    at runTest (deno:runtime/js/40_testing.js:838:11)
    at async runTests (deno:runtime/js/40_testing.js:1089:22)

 FAILURES 

[webhooks] Webhook related tests => ./tests/webhook/webhook.test.ts:5:6

FAILED | 66 passed (98 steps) | 1 failed (2 steps) (2m22s)
error: Test failed

Error: Process completed with exit code 1.
```

**Review by lts20050703 — CHANGES_REQUESTED** [review]
@Skillz4Killz Please run `deno fmt` and fix tests

**Comment by meister03** [comment]
😅 A lot of changes

**Comment by lts20050703** [comment]
sorry skillz you have a lot of merge conflicts because of my parity pr

**Comment by Tricked-dev** [comment]
consider using namespaces like sveltekit so that the user can define if they want to use string or bigint instead of everything having to work their way around it with types

https://kit.svelte.dev/docs/types#app

**Comment by lts20050703** [comment]
please run `deno fmt` lol

**Comment by yuzudev** [comment]
I think you guys should consider using only bigints
Anyone who wants to use strings should fork the library

**Comment by Skillz4Killz** [comment]
Too many issues for supporting bigstring in transformers, the idea is solid and should be applied in helpers #2478

**Pull request closed without merging**
