### PR TITLE
feat: validation plugin

### PR DESCRIPTION
**Pull request by Skillz4Killz**
The validation plugin is a plugin that will validate the args provided in the helpers. Note this will not validate with cache so this can be useful for bots without cache as well. The bots that use cache should also enable the permissions plugin which can add additional validation checks which require cached objects

### CODE REVIEW

**Comment by lts20050703** [comment]
Does this closes #1882 ?

**Comment by Skillz4Killz** [comment]
No this is only part of #1882

**Comment by lts20050703** [comment]
If possible can you try also close #1913 ?

**Comment by Skillz4Killz** [comment]
RIP THIS IS WHAT HAPPENS WHEN PRS DON"T GET MERGED

**Pull request closed without merging**
