### PR TITLE
UNIT TEST editBotStatus

### PR DESCRIPTION
**Pull request by lts20050703**
Closes: #1211

### CODE REVIEW

**Comment by itohatweb** [comment]
Add the test to the mod.ts

**Comment by lts20050703** [comment]
@itohatweb done ✅

**Comment by itohatweb** [comment]
run-tests

**Comment by lts20050703** [comment]
image

**Comment by lts20050703** [comment]
is everything looks good?

**Comment by itohatweb** [comment]
run-tests

**Comment by lts20050703** [comment]
did it work?

**Comment by itohatweb** [comment]
no hrmm cuz benchmarks module

**Comment by Skillz4Killz** [comment]
This PR is missing a couple things. I have to get a chance to look over it. But for example if memory serves it should be using the botUpdate event. Also the event should be set before making the edit call. Another thing is that this is using presence event but i dont see any changes in the intents to add this which confused me. This test will almost always pass because it never tests. I have to get some time to figure out how to handle this appropriately

**Pull request merged**
