### PR TITLE
Release: Discordeno@15.0.0

### PR DESCRIPTION
**Pull request by lts20050703**

### CODE REVIEW

**Comment by itohatweb** [comment]
u sure this is a release and not a bugfix

**Comment by meister03** [comment]
Force Pushes 😨

**Comment by lts20050703** [comment]
> Force Pushes 😨

@meister03 I forgot to fix the test in my "WithReason interface" PR so had to force push to include the fix before release 15

**Comment by lts20050703** [comment]
> u sure this is a release and not a bugfix

@itohatweb https://discord.com/channels/785384884197392384/1018901788696526889/1018910346158805094

**Comment by itohatweb** [comment]
Still a Bugfix .-.

**Review by Skillz4Killz — APPROVED** [review]

**Pull request merged**
