### PR TITLE
add cache members on start option

### PR DESCRIPTION
**Pull request by itohatweb**

### CODE REVIEW

**Comment by Skillz4Killz** [comment]
use case?

**Comment by itohatweb** [comment]
I thought you mentioned that we should add an option to cache members on start in case users don't want to. If thats not the case, I will revert it.

**Comment by Skillz4Killz** [comment]
Ahh no this isn't exactly what i meant. I meant we should consider whether or not we should force all members to be cached from intial queue thing before ready event is run

**Comment by Skillz4Killz** [comment]
Closing this as it needs to be rewroked at a later time as discussed in discord

**Pull request closed without merging**
