### PR TITLE
Adding toJSON function on util/collection

### PR DESCRIPTION
**Pull request by JeanCarlosVR**
Add the function to convert all Map values to JSON, this can be very useful.

### CODE REVIEW

**Comment by itohatweb** [comment]
What if it is a Collection of a Collection

**Comment by JeanCarlosVR** [comment]
> What if it is a Collection of a Collection. Also pls explain the use cases for this.



> What if it is a Collection of a Collection. Also pls explain the use cases for this.

The person may not need those collections within the collection to be converted to JSON; They are also converted to JSON, and if you need it you can simply call that collection that is inside and execute the same converting it into JSON, Personally this is more flexible to the needs.

**Comment by itohatweb** [comment]
image

**Review by JeanCarlosVR — COMMENTED** [review]
Fixing

**Comment by itohatweb** [comment]
> Fixing

Still failing

**Pull request closed without merging**
