### PR TITLE
Add forceSet option for collection

### PR DESCRIPTION
**Pull request by meister03**
Ignores maxSize
```js
collection.set('292892', {name: 'test'}, {forceSet: true})
```

### CODE REVIEW

**Comment by itohatweb** [comment]
Elaborate when this would be used

**Comment by meister03** [comment]
For instance the member collection can be capped to 0. During allowing to save just the bot guild member...

Or when you fetch something and want to keep it for further processing...

**Comment by itohatweb** [comment]
For the 1st there will be a cache update which improves that behaviour.
For the 2nd I'm not sure why you would use a maxed collection for that?

**Comment by meister03** [comment]
When you usually do not want to cache the resource type, but need it for some commands.

**Review by Skillz4Killz — APPROVED** [review]

**Pull request merged**
