### PR TITLE
feat: requiredStructureProperties

### PR DESCRIPTION
**Pull request by Skillz4Killz**
This pr adds a new feature to the library for advanced bot developers. 

The purpose of this feature is for optimizing memory in an easier way than having to customize structures and overriding them. For example, if you simply want to remove some properties you don't use, this would be the ideal way.

```ts
// This example is just to easily show you but you should ideally use an array and loop over the array
cache.requiredStructureProperties.channels.add("topic");
cache.requiredStructureProperties.channels.add("id");
```

This would now make it so that your channels will are ONLY storing the `topic` and `id` properties and nothing else.

### CODE REVIEW

**Comment by ayntee** [comment]
Wouldn't this break some functions (permission checks) if required properties are missing from their respective structures similar to how custom structures can?

**Comment by ayntee** [comment]
Also, I think we should omit the fields from the returned structure for better UX.

**Comment by Skillz4Killz** [comment]
@ayntee @itohatweb ready for review

**Review by ayntee — APPROVED** [review]
LGTM

**Review by itohatweb — APPROVED** [review]

**Comment by itohatweb** [comment]
LGTM but maybe add a `requiredPropsSize` const for the other structures too

**Pull request merged**
