### PR TITLE
fix(types): Update max poll duration and defaults for creating a poll

### LINKED ISSUE #3693: [api-docs] update max poll duration (#6956)
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/5f57e023ddbd24b986d712242f6bbacc77728cce

This is a bot created issue.

### LINKED ISSUE #3700: [api-docs] document poll creation defaults (#6968)
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ff7a1ae31cbc171530f3cd64a826ce8ea350c614

This is a bot created issue.

### PR DESCRIPTION
**Pull request by Fleny113**
Change the max poll duration from 7 days to 32 days.

- Upstream: https://github.com/discord/discord-api-docs/pull/6956
- fixes #3693 
- Upstream: https://github.com/discord/discord-api-docs/pull/6968
- fixes #3700

### CODE REVIEW

**Review by lts20050703 — CHANGES_REQUESTED** [review]
You forgot to switch back to main before creating this branch lol, there are unrelated changes from the attachment title PR

**Comment by Fleny113** [comment]
> You forgot to switch back to main before creating this branch lol, there are unrelated changes from the attachment title PR

Whoops, thanks for noticing

**Review by lts20050703 — APPROVED** [review]
LGTM!

**Review by Skillz4Killz — APPROVED** [review]

**Review by Skillz4Killz — APPROVED** [review]

**Comment by Skillz4Killz** [comment]
@lts20050703 can you add another review and then merge please.

**Review by AwesomeStickz — APPROVED** [review]

**Pull request merged**
