### PR TITLE
add threadName to ExecuteWebhook and sendWebhook

### LINKED ISSUE #2263: [api-docs] Document thread_name for execute webhook (#5007)
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/bf7185bbc6e4c051b394785cb000c3584e76cd1d
No details given.

This is a bot created issue.

### PR DESCRIPTION
**Pull request by lts20050703**
close #2263 
upstream https://github.com/discord/discord-api-docs/commit/bf7185bbc6e4c051b394785cb000c3584e76cd1d

### CODE REVIEW

**Comment by Skillz4Killz** [comment]
Needs unit tests

**Comment by lts20050703** [comment]
image
There's already a unit test (sort of) in `tests/webhook/messages.test.ts`

**Comment by Skillz4Killz** [comment]
You have to add a unit test that uses the threadName property

**Comment by lts20050703** [comment]
@Skillz4Killz can you create forum in the `CACHED_COMMUNITY_GUILD_ID`? threadName is used to create a thread in a forum channel with this name.

**Comment by Skillz4Killz** [comment]
@lts20050703 yes we can

**Pull request closed without merging**
