### PR TITLE
feat!: make desiredProperties properties optional

### PR DESCRIPTION
**Pull request by tavithedev**

### CODE REVIEW

**Review by Fleny113 — CHANGES_REQUESTED** [review]
By making the proprieties of the desiredProprieties object optional and without making the adjustments needed to the transformers Typescript will error on build saying about possibile null values
```
src/transformers/attachment.ts(8,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(9,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(13,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(16,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/attachment.ts(17,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(69,29): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(70,56): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(72,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(73,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(74,31): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(75,32): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(76,42): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(77,34): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(78,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(79,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(80,35): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(81,45): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(82,37): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(83,45): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(84,40): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(85,39): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(86,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(86,33): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(86,58): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(88,63): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(90,62): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(92,67): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(95,56): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(97,38): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(98,32): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(99,48): error TS18048: 'props' is possibly 'undefined'.
src/transformers/channel.ts(102,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/emoji.ts(9,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/emoji.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/emoji.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/emoji.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(36,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(37,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(38,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(40,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(42,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(43,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(44,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(45,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(46,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(47,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(48,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(49,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(50,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(51,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(52,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(54,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(55,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(66,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(73,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(80,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(87,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(94,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(101,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(108,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(109,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(110,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(111,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(121,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(122,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(123,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(124,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(125,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(126,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(127,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(128,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(129,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(130,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(131,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(132,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(133,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(134,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(135,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(136,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(138,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(140,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(141,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(142,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(143,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(144,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/guild.ts(145,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(154,21): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(155,33): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(156,23): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(157,24): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(158,26): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(159,25): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(160,31): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(161,18): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(162,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(163,34): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(164,26): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(165,29): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(166,36): error TS18048: 'props' is possibly 'undefined'.
src/transformers/interaction.ts(167,23): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(13,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(16,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(17,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(19,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(20,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(23,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(24,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(25,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(26,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(27,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(30,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(38,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(42,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/invite.ts(43,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(24,17): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(25,18): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(26,23): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(27,23): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(28,24): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(29,28): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(30,32): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(31,47): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(33,25): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(34,30): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(35,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(35,21): error TS18048: 'props' is possibly 'undefined'.
src/transformers/member.ts(35,35): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(262,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(263,33): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(264,38): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(267,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(268,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(269,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(270,35): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(271,33): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(272,18): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(273,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(277,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(277,9): error TS18048: 'props.interaction' is possibly 'undefined'.
src/transformers/message.ts(281,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(281,9): error TS18048: 'props.interaction' is possibly 'undefined'.
src/transformers/message.ts(286,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(286,9): error TS18048: 'props.interaction' is possibly 'undefined'.
src/transformers/message.ts(290,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(290,9): error TS18048: 'props.interaction' is possibly 'undefined'.
src/transformers/message.ts(294,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(294,9): error TS18048: 'props.interaction' is possibly 'undefined'.
src/transformers/message.ts(301,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(303,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(314,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(317,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(324,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(324,9): error TS18048: 'props.messageReference' is possibly 'undefined'.
src/transformers/message.ts(328,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(328,9): error TS18048: 'props.messageReference' is possibly 'undefined'.
src/transformers/message.ts(332,9): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(332,9): error TS18048: 'props.messageReference' is possibly 'undefined'.
src/transformers/message.ts(339,24): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(341,36): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(348,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(355,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(356,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(356,21): error TS18048: 'props' is possibly 'undefined'.
src/transformers/message.ts(357,29): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(46,26): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(47,28): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(48,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(49,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(50,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(51,35): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(52,28): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(53,37): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(54,29): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(54,44): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(54,67): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(56,37): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(57,45): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(59,54): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(62,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(62,22): error TS18048: 'props' is possibly 'undefined'.
src/transformers/role.ts(62,39): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(16,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(17,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(18,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(19,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(20,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(21,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(22,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(23,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(24,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(25,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(26,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(27,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(28,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/scheduledEvent.ts(29,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInstance.ts(8,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInstance.ts(9,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInstance.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInstance.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInstance.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInviteInstance.ts(8,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInviteInstance.ts(13,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInviteInstance.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/stageInviteInstance.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(8,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(9,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(13,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(16,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(17,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/sticker.ts(18,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(28,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(28,20): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(28,36): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(28,56): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(31,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(32,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(33,21): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(34,27): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(35,30): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(36,32): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(37,25): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(38,24): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(39,31): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(40,25): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(41,25): error TS18048: 'props' is possibly 'undefined'.
src/transformers/user.ts(42,31): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(8,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(9,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(10,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(11,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(12,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(13,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(14,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(15,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(16,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(17,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(23,7): error TS18048: 'props' is possibly 'undefined'.
src/transformers/webhook.ts(28,7): error TS18048: 'props' is possibly 'undefined'.
```

**Review by Fleny113 — COMMENTED** [review]
The TS errors now seems to have been fixed

**Comment by MatthewSH** [comment]
What value is there for making everything optional?

It being not-optional at the moment means that if you want to replace any portion of the properties you have to be extremely intentional about it and ensure you clearly define what you want and what you don't want which, to me, only seems like a positive thing.

**Comment by tavithedev** [comment]
> It being not-optional at the moment means that if you want to replace any portion of the properties you have to be extremely intentional about it and ensure you clearly define what you want and what you don't want which, to me, only seems like a positive thing.

Honestly I don't see a reason why you would want to clearly define what you don't need

**Comment by MatthewSH** [comment]
> Honestly I don't see a reason why you would want to clearly define what you don't need
> 
> EDIT: If we were to use your logic then there would be no default value

There's two ways to define any desired properties, by line or by object.

### Line
```javascript
bot.transformers.desiredProperties['channel']['name'] = true
```

### Object
```javascript
bot.transformers.desiredProperties['channel'] = {
  ...bot.transformers.desiredProperties['channel'],
  name: true
}
```
OR
```javascript
bot.transformers.desiredProperties = {
 ...bot.transformers.desiredProperties,
 channel: {
  ...bot.transformers.desiredProperties.channel,
  name: true
 }
}
```

What you do in the state it is today depends on your needs completely. The way it stands today is it defaults to a very minimal state and it is expected that you will explicitly define any values you need if you need them. The minimal state is not necessarily a good state because every implementation of the library may have different needs.

Being implicit everywhere opens the door for more issues in the logic, more confusion in the desired properties, partial objects when there's expectation of the object itself, etc. 
Being implicit adds 1 more potential value to every single property, it can now be `undefined`.

As stated here:
> If the object accessed or function called using this operator is [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined) or [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null), the expression short circuits and evaluates to [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined) instead of throwing an error.
> — [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

Will this be any major performance hits? Probably not. However it will return `undefined` which now means we're just just checking if a value is either true or false, we're now implicitly checking if it's defined down the entire chain and if it is if it's true or false.

Past that, from a readability standpoint in the code it just doesn't look good, this is completely my opinion but if I had to open up these transformers and see optional chaining everywhere I'd just groan and not want to deal with it. Optional chaining is a great tool, when used in moderation.

In my opinion this just seems like a way to avoid writing the extra code one time and eliminating any structure for the sake of it. If you're just testing a bot, enable all properties with the [`defaultDesiredPropertiesValue`](https://github.com/discordeno/discordeno/blob/main/packages/bot/src/bot.ts#L116). If you really want to do optional on your end, just make your own object that's a [partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) and then merge the objects together through something like:
```javascript
bot.transformers.desiredProperties = {
  ...bot.transformers.desiredProperties,
  ...myPartialProperties,
}
```

**Comment by MatthewSH** [comment]
Based on conversation in Discord, the intent of this PR is to make it where developers don't have to define any properties initially as a part of their one-time setup process. The cons of this PR outweigh the pros, there's multiple ways you can define `desiredProperties` without needing to manually specify every item in the object. On top of adding 2 alternatives which are a little more out there but possible.

**Pull request closed without merging**
