### PR TITLE
ci: move tests into one single workflow file

### PR DESCRIPTION
**Pull request by itohatweb**

### CODE REVIEW

**Comment by H01001000** [comment]
The reasons i split are having separate status badge for each package and it’s easier to see what package goes wrong at pr check

**Comment by itohatweb** [comment]
Do we really need a status badge for every separate package?
Like ideally we should never have it failing tbh.

Also the reason for me moving it to one single file is that I find the separate stuff less friendly to see.

imo that's far better:
Screenshot_20230330_170231

**Comment by H01001000** [comment]
Yea Ik, also should we only trigger push to main?

**Review by H01001000 — APPROVED** [review]

**Review by H01001000 — DISMISSED** [review]
Also remove the badge from readme

**Comment by itohatweb** [comment]
> Yea Ik, also should we only trigger push to main?

I would also run the tests on PRS.

**Comment by itohatweb** [comment]
Yea sounds valid. Have added that.

**Review by Skillz4Killz — DISMISSED** [review]

**Review by Skillz4Killz — APPROVED** [review]

**Review by H01001000 — APPROVED** [review]

**Pull request merged**
