### PR TITLE
Merge Dev into Main

### PR DESCRIPTION
**Pull request by meister03**
Pullrequests:
`Add disabled prop in components for select` - #2341 #2343 #2344 
@breaking `simplify fetchMembers, by removing fetchMembers` - #2339 
`Add new helper function leaveVoiceChannel` - #2342 
`Add 'icon' & 'unicode_emoji' Option to edit role` - #2346 
`Add 'min_length', 'max_length' to ApplicationCommandOption` - #2347 
`Add 'app_permission' on transformer from interaction payload` - #2369

### CODE REVIEW

**Comment by itohatweb** [comment]
Tests are failing.

**Comment by meister03** [comment]
Its happening on the selectComponent.disabled. vscode does not show a issue for it

**Comment by meister03** [comment]
Fixed the type error :)

**Comment by lts20050703** [comment]
Waiting for @Skillz4Killz and/or @itohatweb to merge and release rc46 lol

**Review by lts20050703 — DISMISSED** [review]
LGTM!

**Pull request merged**
