### PR TITLE
chore(deps)!: upgrade all deps to new major versions

### PR DESCRIPTION
**Pull request by MatthewSH**
This goes through every package we can and upgrade it to the latest possible version without breaking the website or packages.

### CODE REVIEW

**Review by H01001000 — CHANGES_REQUESTED** [review]
docusaurus build failed

**Comment by MatthewSH** [comment]
> docusaurus build failed

reverting back to 2.x of Docusaurus due to many issues.

**Comment by H01001000** [comment]
yea that's what i did b4

**Review by MatthewSH — COMMENTED** [review]
Just did a final review of changes. Should be good. Ran through type test and unit test locally. All passing. Release build going through as well. No issues with formatting.

**Review by H01001000 — APPROVED** [review]

**Pull request merged**
