### PR TITLE
feat(handlers): inhibitors for deleteChannel()

### PR DESCRIPTION
**Pull request by itohatweb**
**Please describe the changes this PR makes and why it should be merged:**
Adds check if channel to delete is a rules or updates channel since these cannot be deleted.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ayntee** [comment]
It makes sense for the first parameter to be `guildID` rather than `channelID`. A guild channel is a constituent of a guild, that is, a guild is a larger and bigger element relative to a guild channel. Henceforth, the recommended argument order should be as follows:
`guildID` > `channelID`/`roleID`/`emojiID` > `messageID`

**Comment by itohatweb** [comment]
You're right, then this PR is not breaking

**Comment by ayntee** [comment]
Personally, I am moderately inert about this pull-request, but slightly, I am against this pull-request. It is not the library's obligation to inspect these edge-cases.

**Comment by itohatweb** [comment]
Well it is one invalid request if it is not checked.
`The request was improperly formatted, or the server couldn't understand it`

**Comment by ayntee** [comment]
> Well it is one invalid request if it is not checked.
> `The request was improperly formatted, or the server couldn't understand it`

Discordeno already does a lot of heavy-lifting for users like permission-checking, so on. I don't think this is necessary for users, we already have a rate-limiting handler.

**Review by Skillz4Killz — APPROVED** [review]

**Comment by Skillz4Killz** [comment]
I think this is absolutely needed @ayntee In my opinion this is something that EVERY library should do but only we end up doing. This is essentially rate limiting https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit

**Comment by ayntee** [comment]
> I think this is absolutely needed @ayntee In my opinion this is something that EVERY library should do but only we end up doing. This is essentially rate limiting https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit

Discordeno internally has a queue system for rate-limits.

**Pull request merged**
