### PR TITLE
change(types): move error & file_content to discordeno/

### PR DESCRIPTION
**Pull request by rigormorrtiss**

### CODE REVIEW

**Comment by itohatweb** [comment]
This pr is missing critical changes to other files.

**Comment by itohatweb** [comment]
Also I would prefer that I do this since I plan on moving a ton on files and want to do everything at the same time. But if you really want to do this you can.

**Comment by rigormorrtiss** [comment]
> This pr is missing critical changes to all files using these types.

Can you reopen this pull request? I am working on it.

**Comment by itohatweb** [comment]
If you do this, push when you are finished and let me know, I will reopen it then

**Pull request merged**
