### PR TITLE
BREAKING: Rename getWebhooks to getGuildWebhooks

### PR DESCRIPTION
**Pull request by lts20050703**
Rename getWebhooks to getGuildWebhooks
Move getChannelWebhooks from `helpers/channels` to `helpers/webhooks`
Closes: #2434

### CODE REVIEW

**Review by itohatweb — CHANGES_REQUESTED** [review]
Hey, please resolve the conflicts.
image

**Comment by Skillz4Killz** [comment]
@lts20050703

**Comment by lts20050703** [comment]
@itohatweb Merge conflicts resolved but @Skillz4Killz doesn't like this PR
image

**Review by itohatweb — COMMENTED** [review]
Only reason I could see for the name change would be that `getWebhooks` could cause confusion since users might want to get the webhooks out of a channel with that function.
Although TS would give a small hint that there is also `getChannelWebhooks`.

As of the file moving ig it would be fit better if those functions are in the `helpers/webhooks` directory.

**Comment by Skillz4Killz** [comment]
@lts20050703 needs fixing tests

**Pull request merged**
