### PR TITLE
add: stickerItems field to Message

### PR DESCRIPTION
**Pull request by rigormorrtiss**
Reference: https://github.com/discord/discord-api-docs/pull/3171

### CODE REVIEW

**Review by ayntee — APPROVED** [review]
LGTM

**Comment by ayntee** [comment]
@itohatweb @Skillz4Killz the ref PR has been merged, can we get this merged?

**Comment by itohatweb** [comment]
Oo yea I will add my review when I'm home sorry I forgot about that one.

**Comment by ayntee** [comment]
> Oo yea I will add my review when I'm home sorry I forgot about that one.

No problem, take your time

**Review by Skillz4Killz — APPROVED** [review]

**Review by itohatweb — APPROVED** [review]

**Pull request merged**
