### PR TITLE
add(tests): validateSlashCommands

### PR DESCRIPTION
**Pull request by rigormorrtiss**
image

### CODE REVIEW

**Review by ayntee — APPROVED** [review]

**Comment by itohatweb** [comment]
Hey, please use shorter function names like `[utils] validateSlashCommands invalid name` also please add tests for valid names to go sure. Also please add tests for choices. Slash commands validation are rather complex so I want tests to cover as much as possible.

**Comment by rigormorrtiss** [comment]
> Hey, please use shorter function names like `[utils] validateSlashCommands invalid name`...

Hey there, I figured it would be informative and instructive to new contributors if adequate information about the test suite os provided. Your example provides little to no information about the test suite.

> also please add tests for valid names to go sure.

:confused: I am not sure what that means.

> Also please add tests for choices...

I am currently working on an accompanying pull-request aside from this PR that integrates unit tests for both `validateSlashOptionChoices()` as well as `validateSlashOptions()` utility functions.

**Comment by itohatweb** [comment]
imo these names are too long they take up 2 lines in your terminal I don't like this. Tests are done once and then finished. New contributes most often touch functions they understand so shorter names should not be a problem. 

Valid names eg tests where you validate command names like ping, avatar etc.

**Comment by itohatweb** [comment]
Still can you add tests which test if names are ok? Like `[utils] validateSlashCommands(): valid description`

**Review by Skillz4Killz — APPROVED** [review]

**Review by itohatweb — APPROVED** [review]
LGTM, thanks for the tests

**Pull request merged**
