### PR TITLE
feat: add Discordeno team to codeowners

### PR DESCRIPTION
**Pull request by MatthewSH**
Was thinking about looking at the other sections too. Wanted to ask @H01001000 on that though.

Before we can merge though, the @discordeno/core team may need a permission update so it has write access? There's an error with the core team that makes it invalid. Not sure what's going on there.

### CODE REVIEW

**Comment by MatthewSH** [comment]
@discordeno/core

**Comment by H01001000** [comment]
maybe dd core is not visible?

**Review by H01001000 — CHANGES_REQUESTED** [review]
fix unknown owner, b4 merge

possible solution instead dd/core, keep Skillz4Killz itohatweb

**Comment by Fleny113** [comment]
> maybe dd core is not visible?
> 
> other than that I'm good, tho I may suggest maybe narrowing down the scope to package / component we're more familiar with?

It might be caused by the fact that dd/core does not guarantee the write access to this repo

**Comment by H01001000** [comment]
It should quicker this way

**Review by H01001000 — DISMISSED** [review]

**Review by H01001000 — COMMENTED** [review]
Oh I forgot one change, need exclude team from codeowner

**Comment by itohatweb** [comment]
Please note that the @discordeno/core team is nothing else than decoration. This group has no permissions or what so ever. Main reason is that this stuff is closed beta or paid idk.

**Comment by MatthewSH** [comment]
> Oh I forgot one change, need exclude team from codeowner

What do you mean? The `@discordeno/team` has correct permissions for the repo unless I'm misunderstanding what you're referencing?

> Please note that the @discordeno/core team is nothing else than decoration. This group has no permissions or what so ever. Main reason is that this stuff is closed beta or paid idk.

Good to know, thank you!

**Comment by itohatweb** [comment]
We have many people in the `@discordeno/team` group. Might be worth asking all of them first, whether they are okay with this change, before adding them to the codeowners.

**Comment by MatthewSH** [comment]
> We have many people in the `@discordeno/team` group. Might be worth asking all of them first, whether they are okay with this change, before adding them to the codeowners.

Do you think there would be any complaints? All this really does, or the intent, is give anyone on the team access to approve PRs across this repo so we're not blocked waiting for either you or Skillz to hit the approve button on PRs.

**Comment by H01001000** [comment]
@discordeno/team :)

**Comment by MatthewSH** [comment]
> I mean you just get a bunch of emails, because of the review request, that's all what I'm concerned about.

Ohhhhhhh, that's a completely fair point. I could explicitly add Fleny and I to the CODEOWNERS if that's better for the short term?

**Comment by itohatweb** [comment]
I mean ig, you can also just ignore this repo :rofl:

**Comment by H01001000** [comment]
for now, yea just add us three, and wait their response for other pr

**Comment by MatthewSH** [comment]
> for now, yea just add us three, and wait their response for other pr

I'll create another PR off this to temporarily do that.

**Comment by meister03** [comment]
fine by me

**Review by meister03 — DISMISSED** [review]
LGTM!

**Review by H01001000 — DISMISSED** [review]

**Comment by itohatweb** [comment]
## Update

Awaiting suggestions/concerns etc. until **08.12.2023** if until then no one has raised concerns, this PR will be merged.

> **Note:** This PR will also be merged, if all members of the `@discordeno/team` group approve it.

**Review by ifaoji — APPROVED** [review]

**Review by itohatweb — APPROVED** [review]

**Pull request merged**
