### PR TITLE
add .yarnrc.yml to advanced example solution

### PR DESCRIPTION
**Pull request by Zero-Tools**
The .yarnrc.yml file is needed or else when yarn runs it will attempt to use PnP

### CODE REVIEW

**Comment by Fleny113** [comment]
Can you add the `.yarnrc.yml` to the other examples as well?

**Comment by Zero-Tools** [comment]
@Fleny113 I've added the other files and updated the comment. let me know if there is anything else I can do

**Review by Fleny113 — APPROVED** [review]
The comment in the files still refers to `docket build` even if these projects don't have docker configured. But for the rest seems fine

**Comment by Zero-Tools** [comment]
@Fleny113 I've updated the inline comments

**Review by Fleny113 — APPROVED** [review]

**Review by AwesomeStickz — APPROVED** [review]

**Pull request merged**
